//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ExceptionDelegate.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ExceptionDelegate")
#ifdef RESTRICT_ExceptionDelegate
#define INCLUDE_ALL_ExceptionDelegate 0
#else
#define INCLUDE_ALL_ExceptionDelegate 1
#endif
#undef RESTRICT_ExceptionDelegate

#if !defined (J2ObjCUnitExceptionDelegate_) && (INCLUDE_ALL_ExceptionDelegate || defined(INCLUDE_J2ObjCUnitExceptionDelegate))
#define J2ObjCUnitExceptionDelegate_

@protocol J2ObjCUnitExceptionDelegate < JavaObject >

- (void)execute;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitExceptionDelegate)

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitExceptionDelegate)

#define BrComMobilemindJ2objcUnitExceptionDelegate J2ObjCUnitExceptionDelegate

#endif

#pragma pop_macro("INCLUDE_ALL_ExceptionDelegate")
