//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ExceptionDelegate.java
//

#include "ExceptionDelegate.h"
#include "J2ObjC_source.h"

@interface J2ObjCUnitExceptionDelegate : NSObject

@end

@implementation J2ObjCUnitExceptionDelegate

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, 0, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(execute);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LJavaLangException;" };
  static const J2ObjcClassInfo _J2ObjCUnitExceptionDelegate = { "ExceptionDelegate", "br.com.mobilemind.j2objc.unit", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_J2ObjCUnitExceptionDelegate;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(J2ObjCUnitExceptionDelegate)

J2OBJC_NAME_MAPPING(J2ObjCUnitExceptionDelegate, "br.com.mobilemind.j2objc.unit", "J2ObjCUnit")
