//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ExceptionDelegate.java
//

#ifndef ExceptionDelegate_H
#define ExceptionDelegate_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@protocol J2ObjCUnitExceptionDelegate < JavaObject >

- (void)execute;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitExceptionDelegate)

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitExceptionDelegate)

#define BrComMobilemindJ2objcUnitExceptionDelegate J2ObjCUnitExceptionDelegate


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // ExceptionDelegate_H
