//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/HtmlGenerator.java
//

#ifndef HtmlGenerator_H
#define HtmlGenerator_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@protocol JavaUtilMap;

@interface J2ObjCUnitHtmlGenerator : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithJavaUtilMap:(id<JavaUtilMap>)testFails;

- (NSString *)build;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitHtmlGenerator)

FOUNDATION_EXPORT void J2ObjCUnitHtmlGenerator_initWithJavaUtilMap_(J2ObjCUnitHtmlGenerator *self, id<JavaUtilMap> testFails);

FOUNDATION_EXPORT J2ObjCUnitHtmlGenerator *new_J2ObjCUnitHtmlGenerator_initWithJavaUtilMap_(id<JavaUtilMap> testFails) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT J2ObjCUnitHtmlGenerator *create_J2ObjCUnitHtmlGenerator_initWithJavaUtilMap_(id<JavaUtilMap> testFails);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitHtmlGenerator)

@compatibility_alias BrComMobilemindJ2objcUnitHtmlGenerator J2ObjCUnitHtmlGenerator;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // HtmlGenerator_H
