//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OutputDir.java
//

#include "J2ObjC_source.h"
#include "OutputDir.h"

@interface J2ObjCUnitOutputDir : NSObject

@end

@implementation J2ObjCUnitOutputDir

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(get);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _J2ObjCUnitOutputDir = { "OutputDir", "br.com.mobilemind.j2objc.unit", NULL, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_J2ObjCUnitOutputDir;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(J2ObjCUnitOutputDir)
