//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OutputDirImpl.java
//

#ifndef OutputDirImpl_H
#define OutputDirImpl_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "OutputDir.h"

@interface J2ObjCUnitIOSOutputDirImpl : NSObject < J2ObjCUnitOutputDir >

#pragma mark Public

- (instancetype __nonnull)init;

- (NSString *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitIOSOutputDirImpl)

FOUNDATION_EXPORT void J2ObjCUnitIOSOutputDirImpl_init(J2ObjCUnitIOSOutputDirImpl *self);

FOUNDATION_EXPORT J2ObjCUnitIOSOutputDirImpl *new_J2ObjCUnitIOSOutputDirImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT J2ObjCUnitIOSOutputDirImpl *create_J2ObjCUnitIOSOutputDirImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitIOSOutputDirImpl)

@compatibility_alias BrComMobilemindJ2objcUnitIosOutputDirImpl J2ObjCUnitIOSOutputDirImpl;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // OutputDirImpl_H
