//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OutputDirImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OutputDirImpl")
#ifdef RESTRICT_OutputDirImpl
#define INCLUDE_ALL_OutputDirImpl 0
#else
#define INCLUDE_ALL_OutputDirImpl 1
#endif
#undef RESTRICT_OutputDirImpl

#if !defined (J2ObjCUnitIOSOutputDirImpl_) && (INCLUDE_ALL_OutputDirImpl || defined(INCLUDE_J2ObjCUnitIOSOutputDirImpl))
#define J2ObjCUnitIOSOutputDirImpl_

#define RESTRICT_OutputDir 1
#define INCLUDE_J2ObjCUnitOutputDir 1
#include "OutputDir.h"

@interface J2ObjCUnitIOSOutputDirImpl : NSObject < J2ObjCUnitOutputDir >

#pragma mark Public

- (instancetype)init;

- (NSString *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitIOSOutputDirImpl)

FOUNDATION_EXPORT void J2ObjCUnitIOSOutputDirImpl_init(J2ObjCUnitIOSOutputDirImpl *self);

FOUNDATION_EXPORT J2ObjCUnitIOSOutputDirImpl *new_J2ObjCUnitIOSOutputDirImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT J2ObjCUnitIOSOutputDirImpl *create_J2ObjCUnitIOSOutputDirImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitIOSOutputDirImpl)

@compatibility_alias BrComMobilemindJ2objcUnitIosOutputDirImpl J2ObjCUnitIOSOutputDirImpl;

#endif

#pragma pop_macro("INCLUDE_ALL_OutputDirImpl")
