//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OutputDir.java
//

#ifndef OutputDir_H
#define OutputDir_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@protocol J2ObjCUnitOutputDir < JavaObject >

- (NSString *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitOutputDir)

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitOutputDir)

#define BrComMobilemindJ2objcUnitOutputDir J2ObjCUnitOutputDir


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // OutputDir_H
