//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OutputDir.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OutputDir")
#ifdef RESTRICT_OutputDir
#define INCLUDE_ALL_OutputDir 0
#else
#define INCLUDE_ALL_OutputDir 1
#endif
#undef RESTRICT_OutputDir

#if !defined (J2ObjCUnitOutputDir_) && (INCLUDE_ALL_OutputDir || defined(INCLUDE_J2ObjCUnitOutputDir))
#define J2ObjCUnitOutputDir_

@protocol J2ObjCUnitOutputDir < JavaObject >

- (NSString *)get;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitOutputDir)

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitOutputDir)

#define BrComMobilemindJ2objcUnitOutputDir J2ObjCUnitOutputDir

#endif

#pragma pop_macro("INCLUDE_ALL_OutputDir")
