//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestBehavior.java
//

#ifndef TestBehavior_H
#define TestBehavior_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@protocol JavaUtilList;

@protocol J2ObjCUnitTestBehavior < JavaObject >

- (void)setUp;

- (void)setUpClass;

- (void)tearDown;

- (void)tearDownClass;

- (void)sayWithNSString:(NSString *)message;

- (void)clearMessages;

- (id<JavaUtilList>)getMessage;

- (void)setContextWithId:(id)context;

- (id)getContext;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitTestBehavior)

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitTestBehavior)

#define BrComMobilemindJ2objcUnitTestBehavior J2ObjCUnitTestBehavior


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // TestBehavior_H
