//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestBehavior.java
//

#include "J2ObjC_source.h"
#include "TestBehavior.h"

@interface J2ObjCUnitTestBehavior : NSObject

@end

@implementation J2ObjCUnitTestBehavior

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, 0, -1, -1, -1 },
    { NULL, "V", 0x401, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x401, -1, -1, -1, 3, -1, -1 },
    { NULL, "V", 0x401, 4, 5, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(setUp);
  methods[1].selector = @selector(setUpClass);
  methods[2].selector = @selector(tearDown);
  methods[3].selector = @selector(tearDownClass);
  methods[4].selector = @selector(sayWithNSString:);
  methods[5].selector = @selector(clearMessages);
  methods[6].selector = @selector(getMessage);
  methods[7].selector = @selector(setContextWithId:);
  methods[8].selector = @selector(getContext);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LJavaLangException;", "say", "LNSString;", "()Ljava/util/List<Ljava/lang/String;>;", "setContext", "LNSObject;" };
  static const J2ObjcClassInfo _J2ObjCUnitTestBehavior = { "TestBehavior", "br.com.mobilemind.j2objc.unit", ptrTable, methods, NULL, 7, 0x609, 9, 0, -1, -1, -1, -1, -1 };
  return &_J2ObjCUnitTestBehavior;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(J2ObjCUnitTestBehavior)

J2OBJC_NAME_MAPPING(J2ObjCUnitTestBehavior, "br.com.mobilemind.j2objc.unit", "J2ObjCUnit")
