//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestBehavior.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TestBehavior")
#ifdef RESTRICT_TestBehavior
#define INCLUDE_ALL_TestBehavior 0
#else
#define INCLUDE_ALL_TestBehavior 1
#endif
#undef RESTRICT_TestBehavior

#if !defined (J2ObjCUnitTestBehavior_) && (INCLUDE_ALL_TestBehavior || defined(INCLUDE_J2ObjCUnitTestBehavior))
#define J2ObjCUnitTestBehavior_

@protocol JavaUtilList;

@protocol J2ObjCUnitTestBehavior < JavaObject >

- (void)setUp;

- (void)setUpClass;

- (void)tearDown;

- (void)tearDownClass;

- (void)sayWithNSString:(NSString *)message;

- (void)clearMessages;

- (id<JavaUtilList>)getMessage;

- (void)setContextWithId:(id)context;

- (id)getContext;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitTestBehavior)

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitTestBehavior)

#define BrComMobilemindJ2objcUnitTestBehavior J2ObjCUnitTestBehavior

#endif

#pragma pop_macro("INCLUDE_ALL_TestBehavior")
