//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TestException")
#ifdef RESTRICT_TestException
#define INCLUDE_ALL_TestException 0
#else
#define INCLUDE_ALL_TestException 1
#endif
#undef RESTRICT_TestException

#if !defined (J2ObjCUnitTestException_) && (INCLUDE_ALL_TestException || defined(INCLUDE_J2ObjCUnitTestException))
#define J2ObjCUnitTestException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface J2ObjCUnitTestException : JavaLangRuntimeException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitTestException)

FOUNDATION_EXPORT void J2ObjCUnitTestException_initWithNSString_(J2ObjCUnitTestException *self, NSString *message);

FOUNDATION_EXPORT J2ObjCUnitTestException *new_J2ObjCUnitTestException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT J2ObjCUnitTestException *create_J2ObjCUnitTestException_initWithNSString_(NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitTestException)

@compatibility_alias BrComMobilemindJ2objcUnitTestException J2ObjCUnitTestException;

#endif

#pragma pop_macro("INCLUDE_ALL_TestException")
