//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestBehaviorImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TestBehaviorImpl")
#ifdef RESTRICT_TestBehaviorImpl
#define INCLUDE_ALL_TestBehaviorImpl 0
#else
#define INCLUDE_ALL_TestBehaviorImpl 1
#endif
#undef RESTRICT_TestBehaviorImpl

#if !defined (J2ObjCUnitTestBehaviorImpl_) && (INCLUDE_ALL_TestBehaviorImpl || defined(INCLUDE_J2ObjCUnitTestBehaviorImpl))
#define J2ObjCUnitTestBehaviorImpl_

#define RESTRICT_TestBehavior 1
#define INCLUDE_J2ObjCUnitTestBehavior 1
#include "TestBehavior.h"

@protocol JavaUtilList;

@interface J2ObjCUnitTestBehaviorImpl : NSObject < J2ObjCUnitTestBehavior >

#pragma mark Public

- (instancetype)init;

- (void)clearMessages;

- (id)getContext;

- (id<JavaUtilList>)getMessage;

- (void)sayWithNSString:(NSString *)message;

- (void)setContextWithId:(id)context;

- (void)setUp;

- (void)setUpClass;

- (void)tearDown;

- (void)tearDownClass;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitTestBehaviorImpl)

FOUNDATION_EXPORT void J2ObjCUnitTestBehaviorImpl_init(J2ObjCUnitTestBehaviorImpl *self);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitTestBehaviorImpl)

@compatibility_alias BrComMobilemindJ2objcUnitTestBehaviorImpl J2ObjCUnitTestBehaviorImpl;

#endif

#pragma pop_macro("INCLUDE_ALL_TestBehaviorImpl")
