//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestException.java
//

#ifndef TestException_H
#define TestException_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface J2ObjCUnitTestException : JavaLangRuntimeException

#pragma mark Public

- (instancetype __nonnull)initWithNSString:(NSString *)message;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1
                               withBoolean:(jboolean)arg2
                               withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitTestException)

FOUNDATION_EXPORT void J2ObjCUnitTestException_initWithNSString_(J2ObjCUnitTestException *self, NSString *message);

FOUNDATION_EXPORT J2ObjCUnitTestException *new_J2ObjCUnitTestException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT J2ObjCUnitTestException *create_J2ObjCUnitTestException_initWithNSString_(NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitTestException)

@compatibility_alias BrComMobilemindJ2objcUnitTestException J2ObjCUnitTestException;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // TestException_H
