//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TestBehaviorImpl.java
//

#ifndef TestBehaviorImpl_H
#define TestBehaviorImpl_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "TestBehavior.h"

@protocol JavaUtilList;

@interface J2ObjCUnitTestBehaviorImpl : NSObject < J2ObjCUnitTestBehavior >

#pragma mark Public

- (instancetype __nonnull)init;

- (void)clearMessages;

- (id)getContext;

- (id<JavaUtilList>)getMessage;

- (void)sayWithNSString:(NSString *)message;

- (void)setContextWithId:(id)context;

- (void)setUp;

- (void)setUpClass;

- (void)tearDown;

- (void)tearDownClass;

@end

J2OBJC_EMPTY_STATIC_INIT(J2ObjCUnitTestBehaviorImpl)

FOUNDATION_EXPORT void J2ObjCUnitTestBehaviorImpl_init(J2ObjCUnitTestBehaviorImpl *self);

J2OBJC_TYPE_LITERAL_HEADER(J2ObjCUnitTestBehaviorImpl)

@compatibility_alias BrComMobilemindJ2objcUnitTestBehaviorImpl J2ObjCUnitTestBehaviorImpl;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // TestBehaviorImpl_H
